### ISSUE TITLE
Custom useReducer limitations

### ISSUE THREAD

**Issue by penx** [PacktPublishing/Micro-State-Management-with-React-Hooks#7]
p22, paragraph 2, line 1 reads

> This implementation works almost perfectly as a replacement for `useReducer`

This is in reference to [your custom `useReducer` implementation](https://github.com/PacktPublishing/Micro-State-Management-with-React-Hooks/blob/main/chapter_01/06_usereducer_with_usestate.js) 

You then go on to list 2 subtle differences which I read to imply why the above reads "*almost* perfectly" and not "perfectly".

These differences are  an init function (p22) and inline reducers (p23), however I don't understand why your custom useReducer implementation is not capable of handling these differences.

Here is an example of your custom useReducer implementation using both an init function and inline reducers:

https://codesandbox.io/s/custom-use-reducer-0mnfow?file=/src/App.js

...though perhaps I'm missing something, or have misunderstood what is meant here.

Perhaps a code example to illustrate why the custom implementation works "almost perfectly" and not "perfectly" would be helpful?

**Comment by dai-shi** [comment]
Hi, nice to know that you read this very deeply.
Your assumption is correct. By "almost perfect", it means there are two subtle differences. Especially, the second one is important. (The first one is really subtle, because JS engine optimizes inline functions.)
The second one is what I call the cheat mode, which is described more in detail in this article: https://overreacted.io/a-complete-guide-to-useeffect/#why-usereducer-is-the-cheat-mode-of-hooks
This behavior is used in [use-context-selector](https://github.com/dai-shi/use-context-selector) v1.3, which is used by `react-tracked`.

**Comment by penx** [comment]
> Hi, nice to know that you read this very deeply.

Thanks! The book's great, I'm on chapter 8 now.

I wrote this a couple of years ago and have been meaning to revisit it.

https://medium.com/@penx/a-usestate-and-context-api-pattern-that-prevents-renders-c3ac847cdf48


> The second one is what I call the cheat mode, which is described more in detail in this article: https://overreacted.io/a-complete-guide-to-useeffect/#why-usereducer-is-the-cheat-mode-of-hooks
> This behavior is used in [use-context-selector](https://github.com/dai-shi/use-context-selector) v1.3, which is used by `react-tracked`.

Ah I see now, thanks for taking the time to explain.

In case it's of any use to anyone else, I wrote this example to show how they differ - the bonus is incremented before React's useReducer's dispatch but _after_ the custom userReducer's dispatch:

```js
import { useState, useReducer, useCallback } from "react";

const useReducerCustom = (reducer, initialArg, init) => {
  const [state, setState] = useState(
    init ? () => init(initialArg) : initialArg
  );
  const dispatch = useCallback(
    (action) => setState((prev) => reducer(prev, action)),
    [reducer]
  );
  return [state, dispatch];
};

const init = (count) => ({ count });

const ComponentWithUseReducer = ({ initialCount }) => {
  const [bonus, setBonus] = useState(0);
  const [state, dispatch] = useReducer(
    (prev, delta) => ({ ...prev, count: prev.count + delta + bonus }),
    initialCount,
    init
  );
  const [stateCustom, dispatchCustom] = useReducerCustom(
    (prev, delta) => ({ ...prev, count: prev.count + delta + bonus }),
    initialCount,
    init
  );
  return (
    <>
      <div>Score with useReducer: {state.count}</div>
      <div>Score with custom useReducer: {stateCustom.count}</div>
      <div>
        <button
          onClick={() => {
            setBonus((x) => x + 1);
            dispatch(1);
            dispatchCustom(1);
          }}
        >
          +1
        </button>
      </div>
    </>
  );
};

export default function App() {
  return <ComponentWithUseReducer initialCount={0} />;
}
```
https://codesandbox.io/s/custom-use-reducer-with-date-808kkz?file=/src/App.js:0-1248
